### ISSUE TITLE
Sprint 8 review

### ISSUE THREAD

**Issue by ksheedy** [the-spice-mice/web-app#114]

**Comment by arobillard** [comment]
This sprint went fairly well. I was able to accomplish a lot and get a lot of pages and patterns working together. The one pain point was that two of my tasks were to ensure Jekyll was working on all pages and everything was linked correctly, which was difficult because I was constantly finding new things to add and change.

**Comment by ksheedy** [comment]
In Sprint 8, I was responsible for using the necessary patterns to build the About page and the My Bookings page. I also drafted the written content for the About page and added photos to the photo array pattern. Everything went well generally. When I initially created the My Bookings page, I needed to make an edit to the pattern and in doing so, I broke the Jekyll that was propagating the info in the pattern. This was quickly rectified after my teammate reviewed my code before accepting the changes in my pull request.

**Comment by hollixholton** [comment]
We're really getting down to the wire and this week we were all tasked with starting to create our pages. I'm still trying to get used to the new Jekyll stuff so this week was a little bit stressful. However, I was able to accomplish most of my tasks which was very rewarding. I believe Adam said "Not bad" or something like that.
